Make Container techn optional
plantuml-stdlib/C4-PlantUML pull request #216
Opened 2022-03-18 13:27 UTC by netrounds-fredrik

This change makes the `techn` argument to `Container` and friends optional, similar to how it is optional in `Rel`.

I am not very familiar with this project or plantuml in general, so please review carefully.

2022-03-20 10:39 UTC, kirchsth commented
Hi @netrounds-fredrik

thank you for the PR.
Optional $techn is a good finding/idea (In the meantime C4Model has container and components with optional technology too)

Can you please update the Component and documentation too?

Related to documentation: 
I think it is enough if you delete the line 
" *techn .. technology argument is required, ..."
and replace the remaining (2) *techn with ?techn

Thank you and best regards
Helmut

2022-03-20 10:48 UTC, kirchsth requested changes

2022-03-20 10:48 UTC, kirchsth commented on C4_Container.puml
> +    !$container = $container + '\n\n '+$descr
space after `\n\n ` looks like an "old issue", can you please fix it and remove the space too?

2022-03-20 10:48 UTC, kirchsth commented on C4_Container.puml
> +    !$container = $container + $getSprite($sprite)+'\n'
Can you add a space before and after the + operator that we have the same formatting in a line?

2022-03-21 09:11 UTC, netrounds-fredrik commented
I have addressed the comments. Also made the changes to make the `techn` argument to `Component` optional to align the behavior.

2022-03-21 18:50 UTC, kirchsth approved these changes

2022-03-21 18:50 UTC, merged

2022-03-21 18:51 UTC, kirchsth commented
@netrounds-fredrik thank you for the PR 
Helmut